version: '3.9'

services:
  fastapi:
    container_name: "fastapi_container"
    build:
      context: ..
      dockerfile: docker_pro/fastapi.Dockerfile
    environment:
      - MODULE_NAME=main
      - VARIABLE_NAME=app
      - ASGI_SERVER=uvicorn
      - UVICORN_CMD="uvicorn main:app --host 0.0.0.0 --port 80 --workers 4"
      - GUNICORN_CMD="gunicorn -k uvicorn.workers.UvicornWorker -w 4 main:app -b 0.0.0.0:80"
#    restart: always

  postgres:
    build:
      context: ..
      dockerfile: docker_pro/postgres.Dockerfile
    container_name: postgres_container
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    build:
      context: ..
      dockerfile: docker_pro/pgAdmin.Dockerfile
    container_name: pgadmin_container
#    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=80
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  jenkins:
    build:
      context: ..
      dockerfile: docker_pro/jenkins.Dockerfile
    container_name: jenkins_container
#    restart: on-failure
    volumes:
      - jenkins_data:/var/jenkins_home
      - jenkins_docker_certs:/certs/client:ro

  gitlab:
    build:
      context: ..
      dockerfile: docker_pro/gitlab.Dockerfile
    container_name: gitlab_container
    hostname: gitlab.example.com
    environment:
      - GITLAB_ROOT_PASSWORD="P@ssw0rd"
    ports:
      - "443:443"
      - "8099:80"
      - "22:22"
#    restart: on-failure
    volumes:
      - gitlab_home_config:/etc/gitlab
      - gitlab_home_logs:/var/log/gitlab
      - gitlab_home_data:/var/opt/gitlab
    shm_size: 256m

  nginx:
    build:
      context: ..
      dockerfile: docker_pro/nginx.Dockerfile
    container_name: nginx_container
    ports:
      - "8000:80"
      - "5454:5432"
      - "5050:5050"
      - "8080:8080"
      - "50000:50000"
    restart: always
#    depends_on:
#      - fastapi
#      - postgres
#      - pgadmin
#      - jenkins

volumes:
  postgres_data:
  pgadmin_data:
  nginx_data:
  jenkins_data:
  jenkins_docker_certs:
  gitlab_home_config:
  gitlab_home_data:
  gitlab_home_logs:

networks:
  jenkins: