version: '3.9'

services:
  app:
    image: uvicorn-gunicorn-fastapi:latest
    container_name: "fastapi_container"
    build:
      context: ..
      dockerfile: docker_pro/Dockerfile
    ports:
      - "8088:80"
    environment:
      - UVICORN_CMD="uvicorn main:app --host 0.0.0.0 --port 80 --workers 4"
      - GUNICORN_CMD="gunicorn -k uvicorn.workers.UvicornWorker -w 4 main:app -b 0.0.0.0:80"
    restart: always
