version: '3'
services:
  ubuntu_master:
    build:
      context: ..
      dockerfile: kubernetes_compose/master.Dockerfile
    container_name: ubuntu_master
    command: tail -f /dev/null
    networks:
      ssh_network:
        ipv4_address: 172.28.1.1  # Assign an IP address
    ports:
      - "2222:22"  # Map host port 2222 to container port 22 (SSH)
    volumes:
      - ./master/ssh:/root/.ssh/

  ubuntu_master1:
    build:
      context: ..
      dockerfile: kubernetes_compose/master.Dockerfile
    container_name: ubuntu_master1
    command: tail -f /dev/null
    networks:
      ssh_network:
        ipv4_address: 172.28.1.2  # Assign an IP address
    ports:
      - "2223:22"  # Map host port 2222 to container port 22 (SSH)
    volumes:
      - ./master1/ssh:/root/.ssh/


  ubuntu_master3:
    build:
      context: ..
      dockerfile: kubernetes_compose/master.Dockerfile
    container_name: ubuntu_master3
    command: tail -f /dev/null
    networks:
      ssh_network:
        ipv4_address: 172.28.1.3  # Assign an IP address
    ports:
      - "2224:22"  # Map host port 2222 to container port 22 (SSH)
    volumes:
      - ./master1/ssh:/root/.ssh/

networks:
  ssh_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
